name = "PrettyBroadcastTree"
uuid = "6047ec4b-8f61-4068-a31e-c0fa98a6076d"
authors = ["M.A. Kowalski <mak60@cam.ac.uk>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.4.5"
